### ISSUE TITLE
Failed to compile on Windows

### ISSUE THREAD

**Issue by andylizi** [josh-project/josh#2235]
I tried this command on Windows:

```sh
cargo install josh-cli --locked --git https://github.com/josh-project/josh.git --tag r26.06.11
```

and got this error:

```
Compiling josh-compose v26.6.11
error[E0425]: cannot find function `getuid` in crate `libc`
   --> josh-compose\src\container.rs:257:30
    |
257 |     let uid = unsafe { libc::getuid() };
    |                              ^^^^^^
    |
   ::: C:\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\libc-0.2.186\src\windows\mod.rs:517:5
    |
517 |     pub fn getpid() -> c_int;
    |     ------------------------- similarly named function `getpid` defined here
    |
help: a function with a similar name exists
    |
257 -     let uid = unsafe { libc::getuid() };
257 +     let uid = unsafe { libc::getpid() };
    |

error[E0425]: cannot find function `getgid` in crate `libc`
   --> josh-compose\src\container.rs:258:30
    |
258 |     let gid = unsafe { libc::getgid() };
    |                              ^^^^^^
    |
   ::: C:\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\libc-0.2.186\src\windows\mod.rs:517:5
    |
517 |     pub fn getpid() -> c_int;
    |     ------------------------- similarly named function `getpid` defined here
    |
help: a function with a similar name exists
    |
258 -     let gid = unsafe { libc::getgid() };
258 +     let gid = unsafe { libc::getpid() };
    |

error[E0425]: cannot find function `getuid` in crate `libc`
   --> josh-compose\src\image.rs:26:30
    |
 26 |     let uid = unsafe { libc::getuid() };
    |                              ^^^^^^
    |
   ::: C:\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\libc-0.2.186\src\windows\mod.rs:517:5
    |
517 |     pub fn getpid() -> c_int;
    |     ------------------------- similarly named function `getpid` defined here
    |
help: a function with a similar name exists
    |
 26 -     let uid = unsafe { libc::getuid() };
 26 +     let uid = unsafe { libc::getpid() };
    |

error[E0425]: cannot find function `getgid` in crate `libc`
   --> josh-compose\src\image.rs:27:30
    |
 27 |     let gid = unsafe { libc::getgid() };
    |                              ^^^^^^
    |
   ::: C:\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\libc-0.2.186\src\windows\mod.rs:517:5
    |
517 |     pub fn getpid() -> c_int;
    |     ------------------------- similarly named function `getpid` defined here
    |
help: a function with a similar name exists
    |
 27 -     let gid = unsafe { libc::getgid() };
 27 +     let gid = unsafe { libc::getpid() };
    |

For more information about this error, try `rustc --explain E0425`.
error: could not compile `josh-compose` (lib) due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `josh-cli v26.6.11
```

The previous version `r26.05.08` compiles fine.

This seems to be introduced in d2d19dc10eedca0dc3b0307fcc663b33541ba070. Would it be possible to gate `josh compose` for unix only, since the podman stuff probably won't work on Windows anyway.

**Comment by christian-schilling** [comment]
Hi @andylizi thanks for reporting this.
We where so far not aware anyone is using Josh on Windows so we have no infrastructure setup to test on this platform.
I personally don't have any windows machine to test this on at all.
However, i think it does make sense to support "josh compose" on windows and also potentially podman, for remote building. So instead of gating we should actually fix this on windows.
We have quite a few topics we are working on right now though and very limited bandwidth. So I'm not sure in what timeframe we will be able to address this.

**Comment by vlad-ivanov-name** [comment]
Fixed on master (without podman support, but we can open a separate issue for that).
